name: PHP CS Fixer

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
          tools: php-cs-fixer:v3

      - name: Run PHP CS Fixer
        run: php-cs-fixer fix --allow-risky=yes --dry-run --diff

      - name: Commit changes
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop') }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix styling
